// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_sales_leads",
  title: "List sales leads",
  description: "List sales leads. Optionally filter by stage (new, queued, contacted, responded, qualified, won, lost), industry, or a search string that matches business_name/contact_name/email. Ordered by most recently created.",
  inputSchema: {
    stage: z.string().optional().describe("Lead stage/status filter"),
    industry: z.string().optional().describe("Industry filter (exact match)"),
    search: z.string().optional().describe("Substring search on business_name, contact_name, or email"),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, industry, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("sales_leads").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("status", stage);
    if (industry) q = q.eq("industry", industry);
    if (search) q = q.or(`business_name.ilike.%${search}%,contact_name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} leads.` }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool2({
  name: "get_lead_details",
  title: "Get lead details",
  description: "Fetch a single sales lead with its recent activities (calls, emails, notes).",
  inputSchema: {
    lead_id: z2.string().uuid().describe("Sales lead UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const [lead, activities] = await Promise.all([
      sb.from("sales_leads").select("*").eq("id", lead_id).maybeSingle(),
      sb.from("sales_activities").select("*").eq("lead_id", lead_id).order("created_at", { ascending: false }).limit(50)
    ]);
    if (lead.error) return { content: [{ type: "text", text: lead.error.message }], isError: true };
    if (!lead.data) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    return {
      content: [{ type: "text", text: `${lead.data.business_name} \u2014 ${activities.data?.length ?? 0} activities.` }],
      structuredContent: { lead: lead.data, activities: activities.data ?? [] }
    };
  }
});

// src/lib/mcp/tools/dashboard-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var dashboard_stats_default = defineTool3({
  name: "get_dashboard_stats",
  title: "Get dashboard stats",
  description: "Summary of sales leads by stage plus counts of activities in the last 7 days.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: leads, error } = await sb.from("sales_leads").select("status");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byStage = {};
    for (const r of leads ?? []) byStage[r.status ?? "unknown"] = (byStage[r.status ?? "unknown"] ?? 0) + 1;
    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1e3).toISOString();
    const { count: recentActivities } = await sb.from("sales_activities").select("*", { count: "exact", head: true }).gte("created_at", since);
    const total = leads?.length ?? 0;
    return {
      content: [{ type: "text", text: `Total leads: ${total}. Activities (7d): ${recentActivities ?? 0}.` }],
      structuredContent: { total_leads: total, by_stage: byStage, activities_last_7_days: recentActivities ?? 0 }
    };
  }
});

// src/lib/mcp/tools/recent-activity.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_activity_default = defineTool4({
  name: "list_recent_activities",
  title: "List recent sales activities",
  description: "List the most recent sales activities across all leads (calls, emails, notes, status changes).",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows (default 25)"),
    type: z3.string().optional().describe("Filter by activity type (e.g. call, email, note)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("sales_activities").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Returned ${data?.length ?? 0} activities.` }],
      structuredContent: { activities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-lead-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_lead_note_default = defineTool5({
  name: "add_lead_note",
  title: "Add a note to a lead",
  description: "Append a note-type activity to a sales lead. Use for AI-captured observations, next steps, or context.",
  inputSchema: {
    lead_id: z4.string().uuid().describe("Sales lead UUID"),
    note: z4.string().min(1).describe("Note text")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("sales_activities").insert({ lead_id, type: "note", body: note, created_by: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Note added." }],
      structuredContent: { activity: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wffepkaofnknklqswbwf";
var mcp_default = defineMcp({
  name: "zc-consultants-mcp",
  title: "Z&C Consultants Sales MCP",
  version: "0.1.0",
  instructions: "Tools for the Z&C Consultants outbound sales workspace. Use these to look up sales leads, review recent activity, check dashboard stats, and add notes on behalf of the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, dashboard_stats_default, recent_activity_default, add_lead_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
